language: node_js

node_js:
  - "node"

script:
  - npm run build
  - npm run lint

deploy:
  provider: pages
  target-branch: gh-pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

branches:
  except:
    - gh-pages
